swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /tod:
    # binds a127 app logic to a route
    x-swagger-router-controller: tod
    get:
      tags:
        - tods
      description: Retorna los tipos de objetos documentales
      # used as the method name of the controller
      operationId: todList
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/jsonSchemaArray"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /tod/{id}:
    # binds a127 app logic to a route
    x-swagger-router-controller: tod
    get:
      tags:
        - tods
      description: Retorna el tipo de objeto documental por id
      # used as the method name of the controller
      parameters:
        - name: id
          in: path
          description: "Id del tipo de objeto documental"
          required: true
          type: string
      operationId: todGet
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/jsonSchemaArray"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /tod/{id}/document:
    # binds a127 app logic to a route
    x-swagger-router-controller: tod
    get:
      tags:
        - tods
        - docs
      description: Retorna documentos por tipo de objeto documental
      # used as the method name of the controller
      parameters:
        - name: id
          in: path
          description: "Id del tipo de objeto documental"
          required: true
          type: string
      operationId: docByTodList
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/documentArray"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /document:
    x-swagger-router-controller: doc
    get:
      tags:
        - docs
      description: Retorrna los documentos
      operationId: docList
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/documentArray"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /document/{id}:
    x-swagger-router-controller: doc
    get:
      tags:
        - docs
      description: Retorrna los documentos
      operationId: docRead
      parameters:
        - name: id
          in: path
          description: "Id del documento"
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/document"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
tags:
  - name: tods
    description: Tipo de Objetos Documentales
  - name: docs
    description: Documentos
# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  jsonSchemaArray:
    type: array
    items:
      $ref: "#/definitions/jsonSchema"
  jsonSchema:
    type: object
    properties:
      objName:
        type: string
      _id:
        type: string
      objInterface:
        type: array
        items:
          type: string
      properties:
        type: object
      required:
        type: array
        items:
          type: string
      count:
        type: number
  documentArray:
    type: array
    items:
      $ref: "#/definitions/document"
  document:
    type: object
    properties:
      objName:
        type: string
      _id:
        type: string
      objInterface:
        type: array
        items:
          type: string